#!/usr/bin/env bash
set -euo pipefail

repo_root="${SPORE_REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
scaffold_dir="$repo_root/.spore-scaffold"

echo ""
echo "  ╭─────────────────────────────────────╮"
echo "  │         🌱 spore scaffold            │"
echo "  ╰─────────────────────────────────────╯"
echo ""
echo "  Generating mycelial reference topology..."
echo "  Location: .spore-scaffold/"
echo ""

if [ -d "$scaffold_dir" ]; then
  echo "  ⚠️  .spore-scaffold/ already exists. Overwriting."
  rm -rf "$scaffold_dir"
fi

mkdir -p "$scaffold_dir"

cat > "$scaffold_dir/README.md" << 'EOF'
# Mycelial Topology Reference

This is a reference structure generated by `spore scaffold`. It shows the
full mycelial memory topology - the structure that enables use-driven decay,
proximity graphs, and self-organizing knowledge management.

You don't need to adopt all of this. Compare it to your current repo and
pull in what resonates. The key insight: structure enables measurement,
measurement enables self-organization.

## How to use this

1. Browse the directories below to understand what each layer does
2. Compare to your current repo structure
3. Adopt pieces incrementally (start with INDEX.md - it has the highest ROI)
4. Delete this .spore-scaffold/ directory when you're done exploring

## What makes this topology work

The structure isn't arbitrary. Each piece serves the feedback loop:

```
work happens → retrievals logged → patterns emerge → decay identifies stale →
consolidation compresses → proximity reveals connections → better context next time
```

**INDEX.md files** are the key innovation. They let the agent scan cheaply
(one small file per directory) instead of opening every document. This creates
a measurable "INDEX sufficiency" metric - when the agent needs the full doc
after reading the INDEX, the INDEX needs improvement.

## Minimum viable adoption

If you adopt nothing else, add a root INDEX.md. It gives spore:
- Domain grouping for the proximity graph
- A skip-list for retrieval logging (INDEX reads don't count)
- A foundation for INDEX sufficiency measurement

## Full topology (what you're looking at)

```
your-repo/
├── INDEX.md                    ← root manifest (agent reads first, always)
├── active/                     ← in-flight work (high retrieval frequency)
│   ├── INDEX.md
│   └── [your domains]/
├── archive/                    ← decayed documents (compressed, low-cost storage)
│   ├── INDEX.md
│   └── [consolidated docs]
├── conventions/                ← how work gets done (importance override - never decays)
│   ├── INDEX.md
│   └── [protocols, norms]
├── references/                 ← lookup material (moderate retrieval)
│   ├── INDEX.md
│   └── [guides, patterns]
├── sessions/                   ← data layer (metrics, logs, CSVs)
│   └── [session logs, token data, rp-why scores]
├── .retrieval-log.csv          ← spore data (auto-generated)
├── .interoception-log.csv      ← spore data (auto-generated)
├── .proximity-graph.csv        ← spore data (computed)
├── .trust-state.yaml           ← spore data (auto-generated)
└── .spore.yaml                 ← spore config
```
EOF

mkdir -p "$scaffold_dir/active"
cat > "$scaffold_dir/active/INDEX.md" << 'EOF'
# Active Work

In-flight documents. High retrieval frequency expected. This is where work
lives while it's being actively developed.

Organize by domain - whatever domains make sense for your work. Examples:
- By project (`project-alpha/`, `project-beta/`)
- By function (`design/`, `research/`, `planning/`)
- By team (`frontend/`, `backend/`, `infra/`)

## Why this matters for spore

Documents here are expected to have HIGH retrieval frequency. When they stop
being retrieved, decay kicks in and they become consolidation candidates.
The transition from active → archive is the core lifecycle.

| File | Tags | Summary |
|------|------|---------|
| (your active work goes here) | | |
EOF

mkdir -p "$scaffold_dir/archive"
cat > "$scaffold_dir/archive/INDEX.md" << 'EOF'
# Archive

Consolidated documents. These decayed from active use (retrieval frequency
dropped below the consolidation threshold) and were compressed into summaries.

The full document is preserved here. The INDEX entry in the parent directory
holds the distilled summary. If the agent needs the full doc after reading
the summary, it retrieves from here.

## Why this matters for spore

Archive is the "long-term memory" layer. Documents here:
- Don't count toward active retrieval metrics
- Can be promoted back to active (`spore promote <file>`)
- Prove the system is self-organizing (things move here naturally)

## Consolidation protocol

When `spore consolidate` identifies candidates:
1. Spore presents candidates with decay scores
2. You confirm which ones to archive
3. Spore compresses the document into a summary
4. Full doc moves here, summary stays in the INDEX

| File | Original location | Archived | Summary |
|------|-------------------|----------|---------|
| (archived docs appear here after consolidation) | | | |
EOF

mkdir -p "$scaffold_dir/conventions"
cat > "$scaffold_dir/conventions/INDEX.md" << 'EOF'
# Conventions

How work gets done. Protocols, norms, recipes, team agreements.

These documents should be marked as importance overrides in .spore.yaml -
they never decay regardless of retrieval frequency. They're load-bearing
by definition.

```yaml
# in .spore.yaml
importance_overrides:
  - conventions/
```

## Why this matters for spore

Conventions are the "DNA" of your practice. They:
- Never decay (importance override)
- Anchor the proximity graph (everything connects to conventions)
- Define the rules the agent follows

| File | Tags | Summary |
|------|------|---------|
| (your protocols, norms, and agreements) | | |
EOF

mkdir -p "$scaffold_dir/references"
cat > "$scaffold_dir/references/INDEX.md" << 'EOF'
# References

Lookup material. Guides, patterns, API docs, platform knowledge.

Moderate retrieval frequency expected. These get consulted during specific
tasks but aren't daily-use documents.

## Why this matters for spore

References have a natural retrieval pattern - they spike during certain
task types and go quiet otherwise. Spore learns this pattern. A reference
doc that hasn't been retrieved in 60 days isn't necessarily stale - it
might just be waiting for the right task.

Consider tuning decay rate for this directory if you find references
getting flagged for consolidation too aggressively.

| File | Tags | Summary |
|------|------|---------|
| (your guides, patterns, lookup material) | | |
EOF

mkdir -p "$scaffold_dir/sessions"
cat > "$scaffold_dir/sessions/README.md" << 'EOF'
# Sessions

Data layer. This is where metrics, logs, and CSVs accumulate.

Not every repo needs this directory. If you're using spore purely for
retrieval tracking and consolidation, the dot-files (.retrieval-log.csv etc.)
are sufficient.

This directory is for practitioners who want to track:
- Session-level quality scores (rp-why integration)
- Token spend over time
- Weekly snapshots / accomplishment logs
- Any longitudinal data about their practice

## Why this matters for spore

If rp-why session data lives here, spore can correlate context quality
(what was retrieved) with collaboration quality (rp-why scores). This
closes the full feedback loop: better context → better collaboration.
EOF

cat > "$scaffold_dir/INDEX.md" << 'EOF'
# Repository Index

Quick-lookup manifest. Agent reads this first, always. Then scans directory
INDEX files for tag-based retrieval.

## Directory Map

| Directory | Tags | What lives here | When to consult |
|-----------|------|-----------------|-----------------|
| `active/` | #in-flight #current | In-flight work being actively developed | When working on something current |
| `archive/` | #consolidated #history | Compressed documents that decayed from active use | When INDEX summary isn't sufficient |
| `conventions/` | #rules #protocols #norms | How work gets done: protocols, norms, agreements | Before any action |
| `references/` | #lookup #guides #patterns | Platform knowledge, guides, patterns | During build when needing reference |
| `sessions/` | #data #metrics #logs | Session logs, metrics, longitudinal data | Data analysis, weekly review |

## Key Files (root)

| File | Tags | Purpose |
|------|------|---------|
| `INDEX.md` | #entry-point #manifest | This file - agent reads first |

## Retrieval Protocol

1. Agent reads this INDEX first (always)
2. Based on task context, scan relevant directory INDEX files
3. Open full documents only when the INDEX summary confirms relevance
4. For cross-domain work: scan ALL directory INDEX files, then open relevant docs

## Customize This

Replace the directories above with whatever makes sense for your work.
The key principles:
- Every directory gets an INDEX.md (cheap scanning)
- Tags enable cross-cutting retrieval
- One-liner summaries per file so the agent knows what's inside without opening it
EOF

echo ""
echo "  ✅ Scaffold generated at .spore-scaffold/"
echo ""
echo "  Structure:"
echo "  ────────────────────────────────────"
find "$scaffold_dir" -type f | sort | while read f; do
  relative="${f#$scaffold_dir/}"
  echo "    $relative"
done
echo ""
echo "  ────────────────────────────────────"
echo ""

echo "  Comparing to your current repo:"
echo "  ────────────────────────────────────"

has_root_index=false
has_active=false
has_archive=false
has_conventions=false
has_any_index=false

if [ -f "$repo_root/INDEX.md" ]; then
  has_root_index=true
  echo "  ✓  You have a root INDEX.md"
else
  echo "  ✗  No root INDEX.md (highest ROI addition - start here)"
fi

if [ -d "$repo_root/active" ] || [ -d "$repo_root/src" ] || [ -d "$repo_root/docs" ]; then
  has_active=true
  echo "  ✓  You have active work directories"
else
  echo "  ✗  No obvious active work directory"
fi

if [ -d "$repo_root/archive" ]; then
  has_archive=true
  echo "  ✓  You have an archive/ directory"
else
  echo "  ~  No archive/ yet (created naturally by spore consolidate)"
fi

if [ -d "$repo_root/conventions" ] || [ -d "$repo_root/docs" ] || [ -f "$repo_root/CONTRIBUTING.md" ]; then
  has_conventions=true
  echo "  ✓  You have conventions/norms documented"
else
  echo "  ~  No conventions directory (optional - add when you have team norms)"
fi

index_count=$(find "$repo_root" -name "INDEX.md" -not -path "*/.spore-scaffold/*" -not -path "*/.git/*" 2>/dev/null | wc -l | tr -d ' ')
if [ "$index_count" -gt 0 ]; then
  has_any_index=true
  echo "  ✓  $index_count INDEX.md files found"
else
  echo "  ✗  No INDEX.md files (add one per directory for cheap agent scanning)"
fi

echo ""
echo "  Recommendations:"
echo "  ────────────────────────────────────"

if [ "$has_root_index" = false ]; then
  echo "  1. Add INDEX.md at repo root (copy from .spore-scaffold/INDEX.md, customize)"
  echo "     This alone gives spore domain grouping and retrieval skip-lists."
fi

if [ "$has_any_index" = false ] && [ "$has_root_index" = false ]; then
  echo "  2. Add INDEX.md to each top-level directory"
  echo "     One-liner summaries per file. Enables cheap scanning."
fi

if [ "$has_archive" = false ]; then
  echo "  3. archive/ will be created naturally when you first run spore consolidate"
  echo "     No need to create it manually."
fi

echo ""
echo "  Next steps:"
echo "  ────────────────────────────────────"
echo "  • Browse .spore-scaffold/ to understand the topology"
echo "  • Copy and customize what resonates"
echo "  • Delete .spore-scaffold/ when done: rm -rf .spore-scaffold"
echo "  • Run 'spore init' if you haven't already"
echo ""
